### ISSUE TITLE
Dark mode is scuffed

### ISSUE THREAD

**Issue by onerandomusername** [inotelab/astroverse#125]
I have my browser set to dark mode, but this theme doesn't default to dark mode which is a bit annoying.

I also tried out the search in dark theme and it seems to not inverse colour: https://verse-astro.vercel.app/search/

**Comment by inotelab** [comment]
If you want to rely on the browser's color scheme preference, use the media strategy:
```
// tailwind.config.js
module.exports = {
  darkMode: 'media',
  // ...
}
```
