### ISSUE TITLE
how to display post content in full page?

### ISSUE THREAD

**Issue by rajasekhar-gundala** [inotelab/astroverse#144]
Hello,
Thank you very much for the theme.

How to display single post content in full page? It is showing in middle now.

**Comment by inotelab** [comment]
To display single post content in full width, you need to adjust the layout and prose styles. Here’s a summary of the solution:
	1.	Update the Layout:
Modify BaseLayout.astro to accept a dynamic isSinglePost property. Use w-full max-w-none to make the layout span the full width when isSinglePost is true.
	2.	Adjust Post Page Styles:
In src/pages/posts/[...slug].astro, pass isSinglePost={true} to BaseLayout. Update the <article> class to include prose, ensuring typography optimization while allowing content to scale. Add lg:prose-lg or xl:prose-xl for larger screens if needed.
	3.	Optional Tailwind Config Customization:
Modify @tailwindcss/typography in tailwind.config.js to remove default prose width limits by setting maxWidth: "100%" in the typography plugin.

This approach ensures the single post content spans the full page while keeping clean typography.
